name: Request

on:
  workflow_dispatch:
    inputs:
      application_id:
        type: string
        required: true
        description: Application ID

jobs:
  generate:
    name: "Generate Terraform files and create pull request."
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            token: ${{ secrets.PIPELINE_TOKEN }}

      - run: |
          mkdir -p applications/${{ inputs.application_id }}
          cp example/main.tf applications/${{ inputs.application_id }}/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Create new ${{ inputs.application_id }} application"
          token: ${{ secrets.PIPELINE_TOKEN }}
          body: |
            ApplicationPath:::applications/${{ inputs.application_id }}:::

          commit-message: "Create new ${{ inputs.application_id }} application"
          committer: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          add-paths: "applications/${{ inputs.application_id }}/*"
          branch-suffix: timestamp
          labels: automerge,testmerge
          delete-branch: true
