name: Test outputs

on:
  workflow_dispatch

jobs:
  generate:
    name: "Output steps statues"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo foo
        id: step1_success

      - run: echo bar
        id: step2_success

      - run: exit 2
        id: step3_fail
        continue-on-error: true

      - run: echo baz
        if: false
        id: step4_skip

      - run: exit 2
        id: step4_fail

      - run: echo buzz
        id: step5_never

      - run: echo $CONTEXT
        if: always()
        env:
          CONTEXT: ${{ toJson(steps) }}

