name: PR apply

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/**
      - .gitignore

jobs:
  get_changes:
    runs-on: ubuntu-latest
    name: Get changed files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get all changed directories
        id: changed
        uses: tj-actions/changed-files@v42
        with:
          dir_names: true
          dir_names_max_depth: 3
          json: true
          escape_json: false
          files: 'apps/**'

      - name: debug
        run: echo ${{ steps.changed.outputs.all_changed_files }}
