name: PR apply

on:
  pull_request:
    types:
      - closed

    branches:
      - main
    paths:
      - 'applications/**'

jobs:
  get_application:
    runs-on: ubuntu-latest
    name: Get application from PR title
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    outputs:
      application_id: ${{ steps.getApp.outputs.application }}
    steps:
      - uses: actions/github-script@v7
        id: getApp
        with:
          script: |
            const regex = /\[Label.*\]\[(?<app>.*)\] .*/;
            const title =
              context.payload &&
              context.payload.pull_request &&
              context.payload.pull_request.title
            const application = regex.exec(title).groups['app'];
            core.setOutput('application', application);

  apply:
    uses: ./github/.workflows/wf_apply_tf.yml
    needs: [get_application]
    with:
      application_id: ${{ inputs.application_id }}
